language: r

r:
  - release
  - oldrel # breaks on sf_0.7-2 not available
  - devel

jobs:
  - os: linux
    dist: trusty
  - os: osx
    env:
      - BADGE=osx
      - LD_LIBRARY_PATH=" /opt/local/lib:$LD_LIBRARY_PATH"
      - CPATH="/opt/local/include:$CPATH"

cache:
  - ccache
  - packages

addons:
  apt:
    packages:
      - ccache
      - libgdal1-dev
      - libudunits2-dev    
  homebrew:
    packages:
      - ccache
      - pkg-config
      - gdal
      - gsl
      - udunits
      - llvm

before_install:
# Configure CCACHE
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE)
    gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE)
    g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
# Use llvm to compile on osx
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="$(brew --prefix llvm)/bin:$PATH";
    fi

cache:
  - packages
  - ccache

latex: false
       
r_packages:
  - rgdal

script:
  - R CMD build .
  - R CMD INSTALL . --build

after_script:
  - cat ${PKGNAME}.Rcheck/00check.log
  - cat ${PKGNAME}.Rcheck/00install.out

