language: r

jobs:
  - r: release
    os: linux
    dist: trusty
  - os: osx
    r: release
  - os: osx
    r: oldrel
  - os: osx
    r: devel
      


addons:
  apt:
    packages:
      - ccache
      - libgdal1-dev
      - libudunits2-dev    
  homebrew:
    packages:
      - ccache
      - gdal
      - gsl
      - udunits
      - llvm
      - pkg-config

before_install:
# Configure CCACHE
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE)
    gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE)
    g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars

cache:
  - packages
  - ccache

latex: false
       
r_packages:
  - rgdal

script:
  - R CMD build .
  - R CMD INSTALL . --build

after_script:
  - cat ${PKGNAME}.Rcheck/00check.log
  - cat ${PKGNAME}.Rcheck/00install.out

after_failure:
 - cat errors.txt
